name: test

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main


jobs:
  test:
      runs-on: ubuntu-latest

      steps:
      - name: code checking
        uses: actions/checkout@v4

      - name: download python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install dependencies
        run: pip install -r dependencies.txt

      - name: run tests
        run: pytest -v
